spring.application.name=ferreteria-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/construfacil_ferreteria
spring.datasource.username=consu
spring.datasource.password=Consuelo123#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect